### ISSUE TITLE
The freezing Station dosn't work

### ISSUE THREAD

**Issue by HAQ20** [LightBlueGamer/Lithereal#9] opened 2024-07-06 23:56 UTC
I have the Frozen Litherite Block under the Station but it just dosn't want to work I have no idea why
![image](https://github.com/LightBlueGamer/Lithereal/assets/139398720/e3f89eeb-6457-45a9-8829-b12233e85c1f)
![image](https://github.com/LightBlueGamer/Lithereal/assets/139398720/c0c52647-cd19-41da-b178-93becaa00b23)
I have the version 1.4.3

**Comment by Alexandra-Myers** [comment] 2024-07-07 00:10
have you tried on the proper latest version? I know that Tim replaced the freezing station block entity with a lither collector block entity for testing, and almost certainly stayed that way on versions Stunf released (because you need coordination to do sub releases anyways, also really the 1.5 previews should've been betas not merged into releases)

**Comment by Alexandra-Myers** [comment] 2024-07-07 00:14
Confirmed. 1.4.3 was released with that testing code. 1.4.4 happened way after I fixed that though.

**Closed as completed** 2024-07-07 00:15 UTC
